insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Door verkoop van effecten\nontvangt u €50',-50,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Een vergissing van de bank in uw voordeel,\nu ontvangt €100',100,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Ga terug naar Rue Grande (Dinant)',-10,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','U erft €100',100,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Betaal €10 boete',-10,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Ga verder naar Start',0,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Een vergissing van de bank in uw voordeel,\nu ontvangt €200',200,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Verlaat de gevangenis zonder betalen',0,0,1);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Ga direct naar de gevangenis.\nGa niet langs "start",\nu ontvangt geen €200',0,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Betaal uw verzekeringspremie\n€50',-50,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','U bent jarig en ontvangt van elke speler €10',10,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Terugbetaling inkomstenbelasting,\nu ontvangt €20',20,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Betaal het hospitaal\n€100',-10,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Lijfrente vervalt,\nu ontvangt €100',-100,0,0);
insert into AlgemeenFonds(type,omschrijving,bedrag,aantalPosities,houbij) values ('Algemeen Fonds','Betaal uw doktersrekening\n€50',-50,0,0);
